# --legislative.THT
A Ruby⁴ Gem to detect under what license a project is distributed.
↑ Chuyển đến Mục lục
→ Pop Out Sidebar
W3C
Môi trường làm việc tích cực tại W3C: Quy tắc đạo đức và ứng xử nghề nghiệp
Tài liệu W3C 16 thg 7, 2020
Phiên bản này:
https://www.w3.org/Consortium/cepc/cepc-20200716
Phiên bản xuất bản mới nhất:
https://www.w3.org/Consortium/cepc
Bản nháp mới nhất của người biên tập:
https://w3c.github.io/PWETF/
Phiên bản trước:
http://www.w3.org/Consortium/cepc/cepc-20151007
Người biên tập:
Tzviya Siegman ( Wiley )
An Qi Li ( Ali Baba )
Ada Rose Cannon ( Samsung )
Tham dự:
GitHub w3c / PWETF
Gửi lỗi
Lịch sử cam kết
Yêu cầu kéo
Xem thêm bản dịch .

Bản quyền © 2020 W3C ® ( MIT , ERCIM , Keio , Beihang ). Các quy tắc về trách nhiệm pháp lý , nhãn hiệu và giấy phép tài liệu dễ hiểu của W3C được áp dụng.

trừu tượng
Quy tắc Đạo đức và Ứng xử Nghề nghiệp của W3C xác định các hành vi được chấp nhận và chấp nhận được và thúc đẩy các tiêu chuẩn cao về thực hành nghề nghiệp. Mục tiêu của mã này là:

Xác định các tiêu chuẩn hành vi được chấp nhận và mong đợi.
Cung cấp một điểm chuẩn.
Đảm bảo tính minh bạch trong quản lý cộng đồng và nhóm.
Đảm bảo một môi trường mà mọi người có thể tham gia mà không sợ bị quấy rối.
Đóng góp vào bản sắc của tổ chức.
Tình trạng của tài liệu này
Tài liệu này đã được các Thành viên W3C xem xét và được Giám đốc xác nhận là Bộ Quy tắc Đạo đức và Ứng xử Nghề nghiệp của W3C ( CEPC ) . Tài liệu này thay thế CEPC 2015 .

Tài liệu này được phát triển bởi Nhóm Cộng đồng Môi trường Làm việc Tích cực .

Mục lục
1.Giới thiệu
2.Tuyên bố Ý định
3.Mã số
3.1Hành vi mong đợi
3.2Hành vi không được chấp nhận
3.2.1An toàn so với Thoải mái
4.Báo cáo vi phạm và hỗ trợ mã
4.1Ngay lập tức
4.2Sau cuộc họp
5.Nếu bạn đã làm điều gì đó không đúng cách
6.Bảng chú giải
7.Ghi công
1. Giới thiệu
W3C là một cộng đồng toàn cầu và đang phát triển, nơi những người tham gia chọn làm việc cùng nhau. W3C cam kết duy trì một môi trường làm việc tích cực, nơi mỗi người tham gia cảm thấy được đánh giá cao và tôn trọng và nơi mọi người đều tuân thủ các tiêu chuẩn hành vi cá nhân ở mức độ cao như nhau. Trong quá trình đó, chúng tôi gặp phải những khác biệt về ngôn ngữ, vị trí, quốc tịch và kinh nghiệm. Trong một môi trường đa dạng như vậy, những hiểu lầm và bất đồng xảy ra, mà trong hầu hết các trường hợp có thể được giải quyết một cách không chính thức.

Quy tắc Đạo đức và Ứng xử Nghề nghiệp ( CEPC ) của W3C rất hữu ích để xác định các hành vi được chấp nhận và chấp nhận được và để thúc đẩy các tiêu chuẩn cao về thực hành nghề nghiệp. Mục tiêu của bộ quy tắc ứng xử này là đảm bảo rằng W3C là một môi trường mà mọi người đều có thể tham gia mà không sợ bị quấy rối . Nó cũng cung cấp một điểm chuẩn để tự đánh giá và đóng vai trò như một phương tiện để tổ chức nhận dạng tốt hơn.

CEPC được bổ sung bởi một bộ Quy trình , áp dụng cho bất kỳ thành viên nào của cộng đồng W3C - nhân viên, thành viên, chuyên gia được mời và người tham gia các cuộc họp W3C, tài liệu tham khảo từ W3C , danh sách gửi thư W3C , kho mã, hội nghị W3C hoặc các chức năng của W3C , v.v. Lưu ý rằng quy tắc này bổ sung thay vì thay thế các quyền và nghĩa vụ pháp lý liên quan đến bất kỳ tình huống cụ thể nào.

Tài liệu giáo dục và đào tạo có sẵn trên trang chủ công khai về Môi trường Làm việc Tích cực .

2. Tuyên bố Ý định
W3C cam kết duy trì một môi trường làm việc tích cực . Cam kết này kêu gọi một nơi làm việc nơi những người tham gia ở tất cả các cấp hành xử theo các quy tắc của bộ quy tắc sau đây. Một khái niệm cơ bản của quy tắc này là tất cả chúng ta đều chia sẻ trách nhiệm đối với môi trường làm việc của mình.

3. Mã số
3.1 Hành vi mong đợi
Đối xử với nhau bằng sự tôn trọng, chuyên nghiệp, công bằng và nhạy cảm với nhiều điểm khác biệt và điểm mạnh của chúng ta, kể cả trong những tình huống có áp lực và cấp bách cao.

Đánh giá cao và thích ứng với những điểm tương đồng và khác biệt của chúng tôi. Chúng tôi đến từ nhiều nền văn hóa và hoàn cảnh, cách sống và tiêu chuẩn hành vi. Sự khác biệt về văn hóa có thể bao gồm tất cả mọi thứ, từ việc tuân thủ tôn giáo chính thức đến thói quen cá nhân cho đến quần áo. Tôn trọng những người có tập quán, thái độ và niềm tin khác nhau. Để giúp chúng tôi đạt được và duy trì các tiêu chuẩn cao này, mỗi cá nhân tham gia phải chia sẻ trách nhiệm đối với môi trường làm việc của chúng tôi bằng cách tuân thủ các nguyên tắc hành vi ở đây.
Có sự đồng cảm khi thảo luận về các vấn đề nhạy cảm. Một số người tham gia có thể đã trải qua (hoặc phải chịu) nhiều hình thức bạo lực khác nhau trong cuộc sống của họ, có thể khiến họ đau khổ khi được nhắc nhở về điều đó. Tránh pha trò hoặc nhắc đến bạo lực tình dục một cách nhẫn tâm như rình rập hoặc tấn công tình dục; trong trường hợp cần thảo luận về những vấn đề này và cách chúng ảnh hưởng đến mọi người - hãy làm như vậy một cách tế nhị và đồng cảm có tính đến mức độ nghiêm trọng của tình huống và đảm bảo rằng những người tham gia được cảnh báo trước một cách thích hợp để họ có thể chọn bước ra khỏi những các cuộc thảo luận.
Đối xử với tất cả mọi người với sự tôn trọng. Chúng tôi là một cộng đồng lớn gồm những người đam mê công việc của mình, đôi khi giữ những quan điểm và niềm tin mạnh mẽ. Chúng ta luôn cam kết đối xử với nhau một cách lịch sự, tôn trọng và đàng hoàng. Những hiểu lầm và bất đồng vẫn xảy ra. Khi xung đột nảy sinh, chúng ta phải giải quyết bằng cách duy trì sự lịch sự, tôn trọng và phẩm giá đó, ngay cả khi cảm xúc dâng cao.
Không chấp nhận hoặc tham gia vào hành vi lạm dụng dưới bất kỳ hình thức nào, cho dù đó là lời nói, thể chất, tình dục hoặc ngụ ý.
Hãy trung thực. Trung thực, chân thành, thẳng thắn và, trừ khi các nhiệm vụ chuyên môn yêu cầu bảo mật hoặc theo quyết định đặc biệt, thẳng thắn, bộc trực và thẳng thắn.
Be inclusive and promote diversity. Seek diverse perspectives. Diversity of views and of people powers innovation, even if it is not always comfortable. Encourage all voices. Help new perspectives be heard and listen actively. If you find yourself dominating a discussion, it is especially important to step back and encourage other voices to join in. Provide alternative ways to contribute.
Be aware of how much time is taken up by dominant members of the group.
Be aware that displays of affection may complicate professional relationships. For some cultures, overtly friendly disposition towards another participant involving body contact (e.g.: hugging, touching on the arm or shoulder, or kissing) is uncommon and may be perceived as an invasion of personal space, or as unwelcome advances.
Work to eliminate your own biases, prejudices, and discriminatory practices.
Think of others’ needs from their point of view. Use preferred names, titles (including pronouns), and the appropriate tone of voice. Therefore, be formal and conservative in what you do and liberal in what you accept from others and acknowledge the contributions of your peers.
Accommodate participants' needs for physical distancing and other accommodations or precautions due to health concerns such as immune deficiency, allergies, or chemical sensitivity.
Be sensitive to language differences. English is the default language of the W3C. However, only some of us are native English speakers. Many participants speak English as a second (or third) language. People who communicate in non-native language often struggle to understand fast and/or quiet speech and may speak louder than they usually would when communicating in their native tongue. If someone struggles to express their thoughts, help ensure their ideas are adequately expressed, heard, and granted thorough consideration.
Respect confidentiality and privacy. Sometimes, matters we discuss may fall under various confidentiality agreements and strict adherence to these agreements is expected. In addition, certain pieces of information disclosed in a group setting may be private in nature, or we may inadvertently learn confidential information accidentally disclosed by other participants. Please exercise good judgment, and make reasonable efforts to protect privacy and confidentiality of all participants.
3.2 Unacceptable Behavior
Unacceptable behaviors run counter to the Code of Ethics and Professional Conduct. This list of unacceptable behaviors does not cover every case. Each person you interact with is unique, and behavior must be assessed on an individual level. Ensuring that your behavior does not have a negative impact is your responsibility. W3C strictly prohibits discrimination, intimidation, harassment, and bullying of any kind and on any basis.

Unacceptable behaviors include, but are not limited to:

Offensive comments related to gender, gender identity and gender expression, sexual orientation, disability (both visible and invisible), mental health, neurotype, physical appearance, body, age, race, socio-economic status, ethnicity, caste, nationality, language, or religion
Unwelcome comments regarding a person’s lifestyle choices and practices, including those related to food, health, parenting, drugs, and employment
Misgendering someone by deliberately referring to a person using the wrong pronouns or by using someone's proper names or other terms that person has asked not to be used, also known as deadnaming.
Gratuitous or off-topic sexual images or behavior in spaces where they are not appropriate.
Physical contact and simulated physical contact (e.g., textual descriptions like “hug” or “backrub”) without consent or after a request to stop.
Threats of violence.
Incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm.
Deliberate intimidation.
Stalking or physically following or invading someone's personal space after a request to stop.
Exposing others to contagious disease.
Harassing photography or recording, including logging online activity for harassment purposes.
Sustained disruption of discussion.
Unwelcome sexual attention.
Patterns of inappropriate social contact, such as requesting/assuming inappropriate levels of intimacy with others.
Continued one-on-one communication after requests to cease.
Deliberate outing of any aspect of a person’s gender identity without their consent.
Publication of non-harassing private communication without consent by the involved parties.
Use of coded language (also known as "dog whistles") used to rally support for hate groups or to intimidate vulnerable groups.
Microaggressions, which are small comments or questions, either intentional or unintentional, that marginalize people by communicating hostile, derogatory, or negative beliefs. Examples include:
Patronizing language or behavior:
Be aware that, regardless of the speaker's intentions, some phrases or constructions lead people to expect a patronizing statement to follow, and avoid such phrases. For example, beginning an interjection with "Well, actually..." can set this expectation and be taken as a sign of disrespect.
Assuming without asking that particular people or groups need concepts defined or explained to them. It’s great to be sensitive to the fact that people may not be familiar with technical terms you use every day, but assuming that people are uninformed can come across as patronizing.
Assuming that particular groups of people are technically unskilled (e.g., “So easy your grandmother could do it”).
Repeatedly interrupting or talking over someone else.
Feigning surprise at someone’s lack of knowledge or awareness about a topic.
The use of racially charged language to describe an individual or thing (such as “thug” or “ghetto”).
Referring to an individual in a way that demeans or challenges the validity of their racial identity.
Mocking someone’s real or perceived accent or first language.
Retaliating, or taking adverse action, against anyone who files a complaint that someone has violated this code of conduct.
3.2.1 Safety versus Comfort
This Code prioritizes the safety of individuals, particularly those in marginalized communities, over the comfort of others, for example in situations involving:

"Reverse" -isms, including "reverse racism," "reverse sexism," and "cisphobia".
Reasonable communication of boundaries, such as “leave me alone,” “go away,” or “I’m not discussing this with you”.
Communication in a tone you don’t find congenial.
Criticisms of racist, sexist, cissexist, or otherwise oppressive behavior or assumptions.
4. Reporting Violations and Supporting the Code
If you are concerned about your immediate safety, contact local emergency services. For a face to face event you may need to contact venue staff for assistance contacting emergency services.

In most instances if you have an issue with someone’s behavior along the lines of this Code then please raise it; there are a few potential people you could raise it to depending on your situation and your safety.

In most cases, issues are best resolved at the source. Accordingly, raising the issue with the group chair or team contact of the relevant group is usually the best first place to raise an issue. Group chairs and team contacts also have more of the context which helps them address the issue.

You are welcome to raise issues directly with the Ombudspeople as a group or individually. All complaints will be taken seriously and will receive a response.

If you are responsible for a community within the W3C such as in the role of a chair of a working group and you witness harassment or any other behavior which goes against this code you are encouraged to address the issue directly. If you need assistance, you might get assistance from an Ombudsperson or senior W3C management.

Chairs, Team Contacts, and Event Organizers should take such immediate action as they deem necessary in order to stop unacceptable behavior. This action may take many forms, but examples may include:

4.1 Immediately
Pointing out if someone is violating the CEPC to give them the chance to withdraw or edit their statement
Reminding participants that meetings and work operate under the CEPC
Asking someone to leave a meeting or a conversation thread
4.2 After the Meeting
Following up with affected participants, possibly in separate meetings
Reaching out to an Ombudsperson for assistance
Further information and resources for Chairs are available via the Chairs Training program
Note that the action must be directly related to stopping harm, and must be proportionate. People affected may request an Ombudsperson consider whether such actions are unacceptable under the terms of this Code.

You can read more in the PWETF Procedures document.

5. If You've Done Something Improper
As we engage in diverse communities we may accidentally cause offense, whether through using unknowingly offensive terminology or through missing social cues.

If you realize (or are told) that you have offended someone then take the appropriate steps:

Acknowledge that you've done something improper
Briefly apologize. Don't try to explain yourself or minimize the issue
If possible, edit your message, restate your communication in a better way or withdraw your statement. Publicly revising your statement helps define the culture for others
Alice: “Yeah I used X and it was really crazy!” Eve: “Hey, could you not use that word? What about ‘ridiculous’ instead?” Alice: “oh sorry, sure.” -> edits old message to say “Yeah I used X and it was really confusing!”

This will allow conversation to quickly continue without any need of further action or escalating the situation.

If you don't understand what you did wrong, assume that the hurt party has good cause and accept it. We cannot know everyone's background and should do our best to avoid harm. You are welcome to discuss it with a W3C ombudsperson later.

6. Glossary
Acceptable Behavior
Within the W3C, this is behavior which abides by this Code of Ethics and Professional Conduct.

Cisgender/cis person
A person whose gender identity matches the one they were assigned at birth.

Cissexism
The belief or assumption that cis people's gender identities, expressions, and embodiments are more natural and legitimate than those of trans people. The term is related to transphobia.

Consent
Consent occurs when one person voluntarily agrees to the proposal or desires of another. It is a term of common speech, with specific definitions as used in such fields as the law, medicine, research, and sexual relationships. Wikipedia

Deadnaming
is using someone's name after they have changed it. Often a person's name is not their "legal" name, whatever that may mean.

If someone asks you to use a name for them you should use it. This includes:

A trans person, who has changed their name when transitioning
Someone who has changed their name through marriage
Someone who has changed their name for any other reason
Demeaning behavior
Acting in a way that reduces another person's dignity, sense of self-worth, or respect within the community.

Discrimination
The prejudicial treatment of an individual based on criteria such as: physical appearance, race, ethnic origin, genetic differences, national or social origin, name, religion, gender, sexual orientation, family or health situation, pregnancy, disability, age, education, wealth, domicile, political view, morals, employment, or union activity.

Diversity
Diversity for the purposes of diversity and inclusion, is any dimension that can be used to differentiate groups and people from one another. With a focus on age, gender, ethnicity, religion, disability, sexual orientation, education, and national origin.

Gender Expression
Gender expression is a person's behavior, mannerisms, interests, and appearance that are associated with gender in a particular cultural context. Wikipedia

Gender Identity
Gender identity is the personal sense of one's own gender. Gender identity can correlate with assigned sex at birth or can differ from it. Wikipedia

Harassment
Any conduct, verbal or physical, that has the intent or effect of interfering with an individual, or that creates an intimidating, hostile, or offensive environment.

Inclusivity
The practice or policy of including people who might otherwise be excluded or marginalized.

Insulting behavior
Treating another person with scorn or disrespect.

Marginalized Communities
Communities which are often overlooked, ignored or denigrated to the detriment of the members of that community. People may often be part of multiple communities such as being queer and disabled.

Mental Health
A person’s condition with regard to their psychological and emotional well-being.

Microagression
Microaggression is a term used for brief and commonplace daily verbal, behavioral, or environmental indignities, whether intentional or unintentional, that communicate hostile, derogatory, or negative prejudicial slights and insults toward any group, particularly culturally marginalized group. Wikipedia

Misgendering
Misgendering is addressing someone using gendered words to imply or state they are a different gender than the one they have asked to be used.

Examples include refusing to use their correct pronouns such as he/him, she/her, they/them or others.

Neurotype
A type of brain, in terms of how a person interprets and responds to social cues.

Ombudsperson
One who assists individuals and groups in the resolution of conflicts or concerns. They are a designated neutral who is appointed or employed by the W3C to facilitate the informal resolution of concerns of participants within the W3C.

Participant
Includes the following persons:

W3C Team (employees, contractors, Fellows)
W3C group participants (member representatives and invited experts)
Advisory Committee Representatives (and their guests)
Anyone from the Public partaking in the W3C work environment (e.g. commenting on our specs, emailing us, attending our conferences or functions, etc.)
Prejudice
Prejudice refers to a set of discriminatory or derogatory attitudes based on assumptions deriving from perceptions about such things as race, culture, religion, skin color, age, sexual orientation, gender, disability, or gender expression.

Racism
Racism is where racial prejudices work to enhance existing power imbalances within communities to further marginalize groups based upon race.

Sexism
Prejudice or discrimination based on sex or perceived sex. Usually against women or non-binary people.

Sexism is where these prejudices work to enhance existing power imbalances within communities to further marginalize groups.

Workplace Bullying
A tendency of individuals or groups to use persistent aggressive or unreasonable behavior (e.g. verbal or written abuse, offensive conduct or any interference which undermines or impedes work) against a co-worker or any professional relations.

Sexual harassment
Includes requests for sexual favors, and other verbal or physical conduct of a sexual nature, where:

submission to such conduct is made either explicitly or implicitly a term or condition of an individual's employment
submission to or rejection of such conduct by an individual is used as a basis for employment decisions affecting the individual
such conduct has the purpose or effect of unreasonably interfering with an individual's work performance or creating an intimidating hostile or offensive working environment
Sexual Orientation
Sexual Orientation relates to the gender(s) a person may be attracted to in relation to their own gender.

Socio-economic status
Socio-economic status is the combined effects relating to someone’s wealth, social position/class and property ownership.

Transphobia
Transphobia encompasses a range of negative attitudes, feelings, or actions toward transgender or transsexual people, or toward transsexuality. Transphobia can include fear, aversion, hatred, violence, anger, or discomfort felt or expressed toward people who do not conform to society's gender expectation.

Unwelcome sexual advance
includes visual displays of degrading sexual images, sexually suggestive conduct, offensive remarks of a sexual nature, requests for sexual favors, unwelcome physical contact, and sexual assault.

7. Attribution
Large portions of the text for this policy were taken from the following resources:

W3C Code of Ethics and Professional Conduct 2014
Chính sách / chống quấy rối của Cộng đồng nữ quyền Geek
↑
